// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"a66f234c-9d3b-431c-b47b-63c701710c24\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "a7b44e7f-311c-4232-a0c9-8888034304f");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "25be643b-3be0-46fc-abc5-3b6220ae8800");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
